---

- hosts: localhost
  become: false
  tasks: 
    - command: vagrant up svgcircus chdir={{playbook_dir}}/environments/vagrant/
    - command: vagrant up svgcircus_api chdir={{playbook_dir}}/environments/vagrant/


- hosts: svgcircus
  tasks:
    - apt: update_cache=yes

- hosts: svgcircus
  become: true
  roles:
    - common
    - svgcircus

- hosts: svgcircus_api
  tasks:
    - apt: update_cache=yes
  roles:
    - common
    - svgcircus_api

