---

- hosts: localhost
  become: false
  tasks: 
    - command: vagrant up workspace chdir={{playbook_dir}}/environments/vagrant/


- hosts: workspace
  tasks:
    - apt: update_cache=yes

- hosts: workspace
  become: true
  roles:
    - common

