---

- hosts: svgcircus
  tasks:
    - apt: update_cache=yes

- hosts: svgcircus
  become: true
  roles:
    - common
    - svgcircus

- hosts: svgcircus_api
  tasks:
    - apt: update_cache=yes
  roles:
    - common
    - svgcircus_api

