Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
#  config.vm.box = "ubuntu/trusty64"

  config.vm.define "node1" do |machine|
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "node1"
      vb.memory = 1024 * 2
      vb.cpus = 1
    end
    machine.vm.network "private_network", ip: "172.17.177.21"
    machine.vm.hostname = "node1"
  end

  config.vm.define "node2" do |machine|
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "node2"
      vb.memory = 1024 * 2
      vb.cpus = 1
    end
    machine.vm.network "private_network", ip: "172.17.177.22"
    machine.vm.hostname= "node2"
  end

  config.vm.define 'controller' do |machine|
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "controller"
      vb.memory = 1024 * 2
      vb.cpus = 1
    end
    machine.vm.network "private_network", ip: "172.17.177.11"
    machine.vm.provision :ansible_local do |ansible|
      ansible.playbook       = "vagrant.yml"
      ansible.verbose        = true
      ansible.install        = true
      ansible.limit          = "all" # or only "nodes" group, etc.
      ansible.inventory_path = "vagrant"
    end
  end
end
