# -*- mode: ruby -*-
# vi: set ft=ruby :
#http://ermaker.github.io/blog/2015/11/18/change-insecure-key-to-my-own-key-on-vagrant.html

Vagrant.configure(2) do |config|
  # FIXME This is a third-party dependency (the NSA is watching!)
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :private_network, ip: "192.168.24.48"
  config.vm.network :forwarded_port, guest: 80, host: 9990
  config.vm.network :forwarded_port, guest: 443, host: 9991
  config.vm.hostname = 'local.cnx.org'
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024 * 4
    v.cpus = 1
  end
#  config.ssh.private_key_path = "vagrant_id_rsa"
#  config.ssh.username = "vagrant"
  config.ssh.insert_key = false
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "main.yml"
    ansible.verbose = true
    ansible.inventory_path = "inventory"
  end
#  config.vm.provision "ansible" do |ansible|
#    ansible.inventory_path = "#{ENV['inventory'] || 'inventory'}"
#  end
#  config.ssh.private_key_path = "~/.ssh/cnx_deployment_id_rsa" 
  # Provision the machine using an ansible playbook.
  # See documenation at:
  #  - http://docs.ansible.com/guide_vagrant.html
  #  - https://docs.vagrantup.com/v2/provisioning/ansible.html
#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = "#{ENV['playbook'] || 'main.yml'}"
#    ansible.inventory_path = "#{ENV['inventory'] || 'inventory'}"
#    ansible.limit = 'all'  # The special 'all' group name.
#    ansible.verbose = 'vvv'
#  end
end
