---
- user: name=kardashev group=admin generate_ssh_key=yes

- apt: name={{ item }}
  with_items:
    - git
    - python-pip
    - python3-pip
    - postgresql 
    - libpq-dev 
    - postgresql-client 
    - postgresql-client-common
    - npm
    - ruby


#- git_config: name=user.name value="rich-hart" scope=global
#- git_config: name=user.email value=rich.hart@rice.edu scope=global
#- git_config: name=core.editor value=vim scope=global
